### ISSUE TITLE
Diff-drive big merge TODO list

### ISSUE THREAD

**Issue by po1** [pal-robotics-forks/ros_controllers#30]
A few things to do to get this diff-drive controller upstream:
- [x] document assumptions on the robot model (#35)
- [x] add test for controller load fail scenarii (#34)
- [x] use two spaces for indentation in diffbot model (#32)
- [x] refactor `integrationXX` methods in odometry (#31)
- [x] use backslashes in doxygen (#33)

@bmagyar @efernandez

**Comment by bmagyar** [comment]
I volunteer for all except the test (just to let someone else contribute :P)

**Comment by po1** [comment]
That's all for me, for now.
@bmagyar if you feel like documenting something, or making some unit tests, don't be shy :)

**Comment by po1** [comment]
Somebody ticked 'document assumptions on the robot model', where can I see the result?

**Comment by po1** [comment]
#77 updated, all commits cherry-picked.
